name: multi_future_example
description: An example for multi_future.
version: 0.1.0
# homepage: https://www.example.com

publish_to: 'none'

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  batcher:
    path: '..'
  http:
    git:
      url: 'git://github.com/dart-lang/http.git'
      ref: 'd473635f0dbb72936664696162127c2209986356'

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3