name: multi_future_example
description: An example for multi_future.
version: 0.1.0
# homepage: https://www.example.com

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  batcher:
    path: '..'
  http: ^0.13.0

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3