name: batcher_example
description: An example for batcher.
homepage: https://github.com/hacker1024/batcher.dart/tree/master/example

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  batcher:
    path: '..'
  http: ^0.13.0

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3