name: batcher
description: A package to queue futures and resolve them in batches.
version: 0.1.0
homepage: https://github.com/hacker1024/batcher.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lint: ^1.5.3
  test: ^1.16.7
